# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f009ad9d-535d-4dc6-b7aa-494570d2223f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A16E-20E0";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/other" =
    { device = "/dev/disk/by-uuid/36c8da2c-4169-4d90-bd7b-f995aefd6aa8";
      fsType = "ext4";
    };

  fileSystems."/mnt/projects" =
    { device = "/dev/disk/by-uuid/4a8ee943-ba80-4510-8fae-23805241b383";
      fsType = "ext4";
    };

  fileSystems."/mnt/steam" =
    { device = "/dev/disk/by-uuid/511112dc-1435-441f-9005-33adbe6344f7";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9d424587-2330-4b3b-bef9-066d0309089b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
