{ config, pkgs, ... }:

{
  # Matugen configuration directory
  home.file.".config/matugen/config.toml".text = ''
    [config]
    # Reload applications after theme generation
    reload_apps = true
    reload_apps_list = { waybar = "pkill waybar; waybar &", hyprland = "hyprctl reload", kitty = "kitty @ set-colors --all --configured ~/.config/kitty/theme.conf" }

    [templates.colors]
    input_path = "~/.config/matugen/templates/colors.css"
    output_path = "~/.config/matugen/colors.css"

    [templates.hyprland]
    input_path = "~/.config/matugen/templates/hyprland.conf"
    output_path = "~/.config/hypr/colors.conf"

    [templates.waybar-colors]
    input_path = "~/.config/matugen/templates/waybar-colors.css"
    output_path = "~/.config/waybar/colors.css"

    [templates.rofi-colors]
    input_path = "~/.config/matugen/templates/rofi-colors.rasi"
    output_path = "~/.config/rofi/colors.rasi"

    [templates.kitty]
    input_path = "~/.config/matugen/templates/kitty-theme.conf"
    output_path = "~/.config/kitty/theme.conf"
  '';

  # Template for Hyprland colors
  home.file.".config/matugen/templates/hyprland.conf".text = ''
    # Generated by matugen - DO NOT EDIT MANUALLY
    # Colors extracted from wallpaper

    general {
      col.active_border = rgb({{colors.primary.default.hex_stripped}}) rgb({{colors.secondary.default.hex_stripped}}) 45deg
      col.inactive_border = rgba({{colors.surface_variant.default.hex_stripped}}aa)
    }
  '';

  # Template for Waybar colors (CSS variables)
  home.file.".config/matugen/templates/waybar-colors.css".text = ''
    /* Generated by matugen - DO NOT EDIT MANUALLY */
    /* Colors extracted from wallpaper */

    @define-color bg rgba({{colors.surface.default.red}}, {{colors.surface.default.green}}, {{colors.surface.default.blue}}, 0.95);
    @define-color bg-alt rgba({{colors.surface_container.default.red}}, {{colors.surface_container.default.green}}, {{colors.surface_container.default.blue}}, 0.95);
    @define-color fg #{{colors.on_surface.default.hex_stripped}};
    @define-color fg-alt #{{colors.primary.default.hex_stripped}};
    @define-color border #{{colors.primary.default.hex_stripped}};
    @define-color selected rgba({{colors.primary.default.red}}, {{colors.primary.default.green}}, {{colors.primary.default.blue}}, 0.3);
    @define-color urgent #{{colors.error.default.hex_stripped}};
  '';

  # Template for Rofi colors
  home.file.".config/matugen/templates/rofi-colors.rasi".text = ''
    /* Generated by matugen - DO NOT EDIT MANUALLY */
    /* Colors extracted from wallpaper */

    * {
      bg: rgba({{colors.surface.default.red}}, {{colors.surface.default.green}}, {{colors.surface.default.blue}}, 0.95);
      bg-alt: rgba({{colors.surface_container.default.red}}, {{colors.surface_container.default.green}}, {{colors.surface_container.default.blue}}, 0.95);
      fg: #{{colors.on_surface.default.hex_stripped}};
      fg-alt: #{{colors.primary.default.hex_stripped}};
      border: #{{colors.primary.default.hex_stripped}};
      selected: rgba({{colors.primary.default.red}}, {{colors.primary.default.green}}, {{colors.primary.default.blue}}, 0.3);
      urgent: #{{colors.error.default.hex_stripped}};
    }
  '';

  # Template for Kitty terminal colors
  home.file.".config/matugen/templates/kitty-theme.conf".text = ''
    # Generated by matugen - DO NOT EDIT MANUALLY
    # Colors extracted from wallpaper

    # Background and foreground
    background #{{colors.surface.default.hex_stripped}}
    foreground #{{colors.on_surface.default.hex_stripped}}

    # Cursor colors
    cursor #{{colors.primary.default.hex_stripped}}
    cursor_text_color #{{colors.on_primary.default.hex_stripped}}

    # Selection colors
    selection_background #{{colors.primary_container.default.hex_stripped}}
    selection_foreground #{{colors.on_primary_container.default.hex_stripped}}

    # URL underline color
    url_color #{{colors.primary.default.hex_stripped}}

    # Black
    color0 #{{colors.surface_variant.default.hex_stripped}}
    color8 #{{colors.on_surface_variant.default.hex_stripped}}

    # Red
    color1 #{{colors.error.default.hex_stripped}}
    color9 #{{colors.error.default.hex_stripped}}

    # Green
    color2 #{{colors.tertiary.default.hex_stripped}}
    color10 #{{colors.tertiary.default.hex_stripped}}

    # Yellow
    color3 #{{colors.secondary.default.hex_stripped}}
    color11 #{{colors.secondary.default.hex_stripped}}

    # Blue
    color4 #{{colors.primary.default.hex_stripped}}
    color12 #{{colors.primary.default.hex_stripped}}

    # Magenta
    color5 #{{colors.primary_container.default.hex_stripped}}
    color13 #{{colors.primary_container.default.hex_stripped}}

    # Cyan
    color6 #{{colors.secondary_container.default.hex_stripped}}
    color14 #{{colors.secondary_container.default.hex_stripped}}

    # White
    color7 #{{colors.on_surface.default.hex_stripped}}
    color15 #{{colors.on_surface.default.hex_stripped}}
  '';

  # General colors CSS (useful reference)
  home.file.".config/matugen/templates/colors.css".text = ''
    /* Generated by matugen - DO NOT EDIT MANUALLY */
    /* Material Design 3 colors from wallpaper */

    :root {
      /* Primary */
      --primary: #{{colors.primary.default.hex_stripped}};
      --on-primary: #{{colors.on_primary.default.hex_stripped}};
      --primary-container: #{{colors.primary_container.default.hex_stripped}};
      --on-primary-container: #{{colors.on_primary_container.default.hex_stripped}};

      /* Secondary */
      --secondary: #{{colors.secondary.default.hex_stripped}};
      --on-secondary: #{{colors.on_secondary.default.hex_stripped}};
      --secondary-container: #{{colors.secondary_container.default.hex_stripped}};
      --on-secondary-container: #{{colors.on_secondary_container.default.hex_stripped}};

      /* Tertiary */
      --tertiary: #{{colors.tertiary.default.hex_stripped}};
      --on-tertiary: #{{colors.on_tertiary.default.hex_stripped}};
      --tertiary-container: #{{colors.tertiary_container.default.hex_stripped}};
      --on-tertiary-container: #{{colors.on_tertiary_container.default.hex_stripped}};

      /* Error */
      --error: #{{colors.error.default.hex_stripped}};
      --on-error: #{{colors.on_error.default.hex_stripped}};

      /* Surface */
      --surface: #{{colors.surface.default.hex_stripped}};
      --on-surface: #{{colors.on_surface.default.hex_stripped}};
      --surface-variant: #{{colors.surface_variant.default.hex_stripped}};
      --on-surface-variant: #{{colors.on_surface_variant.default.hex_stripped}};
      --surface-container: #{{colors.surface_container.default.hex_stripped}};
    }
  '';
}
